#!/bin/bash

function _iswin() {
  [ "${OS-'None'}" = "Windows_NT" ]
}

################################################################################
# USUAL STUFF
################################################################################
_iswin && {                                                                 \
  alias pkill='tskill';                                                     \
}

alias l="eza --icons --group-directories-first"
alias ll="eza -al --icons --group-directories-first"
alias la="eza -a --git --icons --group-directories-first"
alias lt="eza --tree --git --icons --group-directories-first"

# alias l="ls --color --group-directories-first"
# alias ll="ls --color -al --group-directories-first"
# alias la="ls --color -a --group-directories-first"
# alias lt="ls --color --group-directories-first"

alias grep='grep --color'
alias du='/usr/bin/du -hc --max-depth=1'
alias df='df -h'
alias shred='shred -u'
alias hd=hexyl
alias tree='lt'

alias pipupgrade='python -m pip install --upgrade pip'
alias pip='python -m pip'
alias pip3='python3 -m pip'

################################################################################
# ALTERNATIVES
################################################################################

alias cat=bat
alias gemini='npx @google/gemini-cli'

################################################################################
# VIM / GVIM
################################################################################
# use tabs to open multiple files with vim
alias vim='nvim -p'


################################################################################
# PERSONAL SHORTCUTS
################################################################################
# Short date
alias sdate='date +%d.%m.%y-%H.%M.%S'

alias livelog='watch --color -n 2 git --no-pager lag --color=always -35'

alias pytest='pytest -v'

# TLA+ tools
if _iswin; then
  _tlatools="$(cygpath -m ${SCOOP})/apps/tlaplus-toolbox/current/tla2tools.jar"
else
  _tlatools="${HOME}/.local/share/applications/tla2tools.jar"
fi
alias tlc="java -XX:+UseParallelGC -jar ${_tlatools} -workers auto"
alias pcal="java -cp ${_tlatools} pcal.trans"
alias tla2tex="java -cp ${_tlatools} tla2tex.TLA -shade -latexCommand lualatex"
alias sany="java -cp ${_tlatools} tla2sany.SANY"

# psyko
if _iswin; then
  function givemepsyko() {
    local ksdir=${KRONOSAFE_INSTALL_DIR}
    local version="9.5.0"

    local psykover="psyko-${version}"
    local ksimver="ksim-${version}"
    local psykopath="${ksdir}/${psykover}/bin"

    _pathidx=${path[(Ie)${psykopath}]}

    if [[ ${_pathidx} = 0 ]];
    then
      # not in path: add it
      path=(${psykopath} $path)
      export PATH
      alias psyko-ksim="psyko -p ksim --kernel-dir=${ksdir}/${ksimver}"
      echo "Added ${psykover} to PATH"
    else
      # remove from path
      path[${_pathidx}]=()
      export PATH
      unalias psyko-ksim
      echo "Removed ${psykover} from PATH"
    fi
  }
fi

# mount Google Drive with rclone
alias gdrivemount='rclone mount --daemon gdrive: ${HOME}/gdrive'

################################################################################
# FUNCTIONS
################################################################################
# alias for "cd" then "ls"
function c {
    if [[ -z $* ]];
    then
        cd && l;
    else
        cd "$*" && l ;
    fi
}

# Run a command and issue a notification when it completes. Requires notify-py
# and Python
function notify() {
  ( "$@" && notifypy --title "✅ Command successful" --message "${@}" \
                     --applicationName "Console notify" ) || \
  notifypy --title "❌ Command failed" --message "${*}" \
           --applicationName "Console notify"
}

# Run a command in a loop until it fails
function runtilldeath() {
  local _tmpfile
  local _iter
  local _greem _endcolor
  _green="\e[32m"
  _endcolor="\e[0m"
  _tmpfile=$(mktemp rununtil.XXX)
  _iter=0
  echo "Running. Output redirected to ${_tmpfile}..."
  echo ""
  while "${@}" &> "${_tmpfile}";
  do
    _iter=$((_iter + 1))
    echo -ne "\r"
    echo -ne "Ran ${_green}${_iter}${_endcolor} times successfully, continue..."
  done
  echo -e "\nExecution failed after ${_iter} successful runs."
  echo "Output of last run is logged in ${_tmpfile}"
}

################################################################################
# UPDATE TOOLS
################################################################################

function _warnmsg() {
  printf "\033[1;33m%s\033[0m\n" "${*}"
}
function _okmsg() {
  printf "\033[1;32m%s\033[0m\n" "${*}"
}

function fullupdate() {
  ( set -euo pipefail
  _lastupdate_file="${HOME}/.config/.last_update"
  _pendingupdate_lockfile="${HOME}/.config/.pending_fullupdate"

  touch "${_pendingupdate_lockfile}"
  chezmoi update

  echo -e ""

  if ( chezmoi git -- diff-index --quiet HEAD &> /dev/null );
  then
    _okmsg "✅ chezmoi working tree is clean"
  else
    _warnmsg "⚠️ chezmoi working tree is dirty: consider pushing!"
  fi


  touch "${_lastupdate_file}"
  rm -f "${_pendingupdate_lockfile}"

  _okmsg "All done."
  )
}

function maybeupdate()
{
  python3 "${HOME}/.config/update.py" || fullupdate
}

################################################################################
